
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfyvswnoijljoangojpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeXZzd25vaWpsam9hbmdvanBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzUxNDAsImV4cCI6MjA2MzUxMTE0MH0.3exx6-Y_Hxv1piNSekjMEWDmr14qlqKwkZ813Tl8Xcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
